# Generated by Django 4.0.6 on 2022-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('User', models.IntegerField(primary_key=True, serialize=False, verbose_name='User')),
                ('Level_of_Study', models.CharField(choices=[('UG', 'Undergraduate'), ('PGT', 'Postgraduate')], max_length=3)),
                ('Year_of_Course', models.IntegerField(verbose_name='Year of Course')),
                ('Registration_Status', models.CharField(max_length=100, verbose_name='Registration Status')),
                ('Course_Title', models.CharField(max_length=100, verbose_name='Course Title')),
                ('Course_Code', models.SlugField(max_length=6, verbose_name='Course Code')),
                ('Teaching_Sessions', models.IntegerField(verbose_name='Teaching Sessions')),
                ('Attended', models.IntegerField(verbose_name='Sessions Attended')),
                ('Explained_Absences', models.IntegerField(verbose_name='Explained Absences')),
                ('Non_Attendance', models.IntegerField(verbose_name='Non Attendance')),
                ('Percentage_Attendance', models.FloatField(verbose_name='% Attendance')),
                ('Percentage_Attendance_Unexcused', models.FloatField(verbose_name='Percentage attendance (Unexcused)')),
                ('Last_Attendence', models.DateTimeField(verbose_name='Last Attendance')),
                ('Submitted', models.IntegerField(verbose_name='Submitted')),
                ('Explained_Non_Submission', models.IntegerField(verbose_name='Explained Non Submission')),
                ('Non_Submission', models.IntegerField(verbose_name='Non Submission')),
                ('Within_Late_Period_Flag', models.IntegerField(verbose_name='Within Late Period Flag')),
                ('Percentage_Submitted', models.FloatField(verbose_name='Percentage Submitted')),
                ('Last_Submitted', models.DateTimeField(verbose_name='Last Submitted')),
                ('Academic_Advising_Sessions', models.IntegerField(verbose_name='Academic Advising Sessions')),
                ('Attended_AA', models.IntegerField(verbose_name='Attended AA')),
                ('Explained_Non_Attendances_AA', models.IntegerField(verbose_name='Explained Non Attended AA')),
                ('Non_Attendances_AA', models.IntegerField(verbose_name='Non Attendances AA')),
                ('Attendance_Not_Recorded_AA', models.IntegerField(verbose_name='Attendance Not Recorded AA')),
                ('Percentage_Attendance_AA', models.FloatField(verbose_name='Percentage Attendance AA')),
                ('Last_Attended_AA', models.DateTimeField(verbose_name='Last Attended AA')),
            ],
        ),
    ]
